import React, { useCallback, useEffect, useRef, useState } from 'react';
import Header from '../components/Header';
import Footer from '../components/Footer';
import { useSEO } from '../hooks/useSEO';
import {
  hitTopOpaqueItem,
  invalidateImageAlphaCache,
} from '../utils/imageAlphaHitTest';
import '../styles/MoveThingsAroundPage.css';

/**
 * Images live in public/assets/movethingsaround/. Filenames are listed in manifest.json,
 * generated by scripts/write-movethings-manifest.js (prestart / prebuild).
 */
function shuffleInPlace(arr) {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

function buildItemsFromFiles(files) {
  const names = [...files];
  shuffleInPlace(names);

  const vw = typeof window !== 'undefined' ? window.innerWidth : 1100;
  const vh = typeof window !== 'undefined' ? window.innerHeight : 800;
  const boardMaxW = Math.min(1100, vw - 32);
  const approxImg = Math.min(200, vw * 0.42);
  const pad = 16;
  const boardH = Math.max(280, vh - 280);

  return names.map((file, i) => {
    const maxX = Math.max(pad, boardMaxW - approxImg - pad);
    const maxY = Math.max(pad, boardH - approxImg - pad);
    const x = pad + Math.random() * maxX;
    const y = pad + Math.random() * maxY;
    return {
      id: file,
      src: `/assets/movethingsaround/${encodeURIComponent(file)}`,
      x,
      y,
      z: i + 1,
    };
  });
}

function MoveThingsAroundPage() {
  const boardRef = useRef(null);
  const imgRefs = useRef(new Map());
  const itemsRef = useRef([]);
  const maxZRef = useRef(1);
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [loadError, setLoadError] = useState(false);
  const [showCheer, setShowCheer] = useState(false);
  const cheerTimerRef = useRef(null);
  const completedMovesRef = useRef(0);
  const dragRef = useRef(null);

  itemsRef.current = items;

  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  useEffect(() => {
    return () => {
      if (cheerTimerRef.current) {
        window.clearTimeout(cheerTimerRef.current);
      }
    };
  }, []);

  useEffect(() => {
    let cancelled = false;
    async function load() {
      try {
        const res = await fetch('/assets/movethingsaround/manifest.json', {
          cache: 'no-store',
        });
        if (!res.ok) throw new Error('manifest missing');
        const files = await res.json();
        if (!Array.isArray(files)) throw new Error('bad manifest');
        if (cancelled) return;
        const next = buildItemsFromFiles(files);
        setItems(next);
        maxZRef.current = Math.max(files.length, 1);
        setLoadError(false);
      } catch {
        if (!cancelled) {
          setLoadError(true);
          setItems([]);
        }
      } finally {
        if (!cancelled) setLoading(false);
      }
    }
    load();
    return () => {
      cancelled = true;
    };
  }, []);

  useSEO({
    title: 'Move things around | citla.li/movethingsaround',
    description: 'Drag photos around the page. Click a photo to bring it to the front.',
    keywords: 'citla.li, drag, photos',
    canonicalUrl: 'https://citla.li/movethingsaround',
    ogTitle: 'Move things around',
    ogDescription: 'Drag photos; click to bring one to the front.',
    ogImage: 'https://citla.li/og-image.gif',
    twitterTitle: 'Move things around',
    twitterDescription: 'Drag photos around.',
    twitterImage: 'https://citla.li/og-image.gif',
  });

  const bringToFront = useCallback((id) => {
    maxZRef.current += 1;
    const nextZ = maxZRef.current;
    setItems((prev) =>
      prev.map((it) => (it.id === id ? { ...it, z: nextZ } : it))
    );
  }, []);

  useEffect(() => {
    const onMove = (e) => {
      const d = dragRef.current;
      if (!d || !boardRef.current || !d.imgEl) return;
      document.body.style.cursor = 'grabbing';

      if (!d.didMove) {
        const dx = e.clientX - d.startClientX;
        const dy = e.clientY - d.startClientY;
        if (Math.hypot(dx, dy) > 12) {
          d.didMove = true;
        }
      }

      const boardRect = boardRef.current.getBoundingClientRect();
      let nx = e.clientX - boardRect.left - d.offsetX;
      let ny = e.clientY - boardRect.top - d.offsetY;

      const imgRect = d.imgEl.getBoundingClientRect();
      const approxW = imgRect.width;
      const approxH = imgRect.height;
      const pad = 8;
      nx = Math.max(
        pad,
        Math.min(nx, Math.max(pad, boardRect.width - approxW - pad))
      );
      ny = Math.max(
        pad,
        Math.min(ny, Math.max(pad, boardRect.height - approxH - pad))
      );

      setItems((prev) =>
        prev.map((it) => (it.id === d.id ? { ...it, x: nx, y: ny } : it))
      );
    };

    const onUp = () => {
      const d = dragRef.current;
      if (d?.didMove) {
        completedMovesRef.current += 1;
        if (completedMovesRef.current === 2) {
          setShowCheer(true);
          if (cheerTimerRef.current) {
            window.clearTimeout(cheerTimerRef.current);
          }
          cheerTimerRef.current = window.setTimeout(() => {
            setShowCheer(false);
            cheerTimerRef.current = null;
          }, 2000);
        }
      }
      dragRef.current = null;
      document.body.style.cursor = '';
    };

    window.addEventListener('pointermove', onMove);
    window.addEventListener('pointerup', onUp);
    window.addEventListener('pointercancel', onUp);
    return () => {
      window.removeEventListener('pointermove', onMove);
      window.removeEventListener('pointerup', onUp);
      window.removeEventListener('pointercancel', onUp);
    };
  }, []);

  useEffect(() => {
    const board = boardRef.current;
    if (!board) return;

    let raf = null;
    const onBoardMove = (e) => {
      if (dragRef.current) return;
      if (raf) return;
      raf = requestAnimationFrame(() => {
        raf = null;
        const hit = hitTopOpaqueItem(
          itemsRef.current,
          e.clientX,
          e.clientY,
          (id) => imgRefs.current.get(id)
        );
        board.style.cursor = hit ? 'grab' : 'default';
      });
    };

    const onLeave = () => {
      if (!dragRef.current) board.style.cursor = 'default';
    };

    board.addEventListener('pointermove', onBoardMove);
    board.addEventListener('pointerleave', onLeave);
    return () => {
      board.removeEventListener('pointermove', onBoardMove);
      board.removeEventListener('pointerleave', onLeave);
      if (raf) cancelAnimationFrame(raf);
    };
  }, []);

  const handleBoardPointerDownCapture = useCallback(
    (e) => {
      if (e.button !== 0 && e.pointerType === 'mouse') return;

      const hit = hitTopOpaqueItem(
        items,
        e.clientX,
        e.clientY,
        (id) => imgRefs.current.get(id)
      );
      if (!hit) return;

      e.preventDefault();
      e.stopPropagation();

      bringToFront(hit.item.id);

      if (!boardRef.current) return;
      const boardRect = boardRef.current.getBoundingClientRect();
      dragRef.current = {
        id: hit.item.id,
        offsetX: e.clientX - boardRect.left - hit.item.x,
        offsetY: e.clientY - boardRect.top - hit.item.y,
        imgEl: hit.img,
        startClientX: e.clientX,
        startClientY: e.clientY,
        didMove: false,
      };
    },
    [items, bringToFront]
  );

  return (
    <div className="movethings-page">
      <Header />
      <main className="movethings-main">
        <p className="movethings-prototype">
          prototype for moveThingsAround.com coming soon
        </p>
        <h1 className="movethings-title">move things around</h1>
        <div
          ref={boardRef}
          className="movethings-board"
          role="application"
          aria-label="Draggable photo board"
          onPointerDownCapture={handleBoardPointerDownCapture}
        >
          {!loading &&
            !loadError &&
            items.map((it) => (
              <div
                key={it.id}
                className="movethings-item"
                style={{
                  left: it.x,
                  top: it.y,
                  zIndex: it.z,
                }}
              >
                <img
                  ref={(el) => {
                    if (el) imgRefs.current.set(it.id, el);
                    else imgRefs.current.delete(it.id);
                  }}
                  src={it.src}
                  alt=""
                  className="movethings-img"
                  draggable={false}
                  onLoad={(e) => invalidateImageAlphaCache(e.currentTarget)}
                />
              </div>
            ))}
        </div>
      </main>
      <Footer />
      {showCheer && (
        <div className="movethings-cheer-overlay" role="status" aria-live="polite">
          <p className="movethings-cheer-text">youre doing it!</p>
        </div>
      )}
    </div>
  );
}

export default MoveThingsAroundPage;
